import os
import json
from pathlib import Path
from typing import List, Dict, Any

# We use the same official client
from huggingface_hub import InferenceClient

class SummarizerAgent:
    """
    This agent is responsible for Task 5:
    1. Taking a query and a list of retrieved documents (context).
    2. Synthesizing them into a structured summary.
    3. Citing the sources for each piece of information.
    """
    
    MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
    
    def __init__(self):
        # Try to get the API key from the environment
        api_key_from_env = os.getenv("HUGGINGFACE_API_KEY")
        
        # ⬇️ *** OR, PASTE YOUR KEY HERE (less secure) *** ⬇️
        pasted_api_key = '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' # Your key
        # ----------------------------------------------------

        self.api_key = pasted_api_key if pasted_api_key else api_key_from_env
            
        if not self.api_key:
            print("❌ Error: HUGGINGFACE_API_KEY not found.")
            raise ValueError("HUGGINGFACE_API_KEY not set")
            
        self.client = InferenceClient(token=self.api_key)
        print(f"✅ SummarizerAgent initialized. Using model: {self.MODEL_NAME}")

    def _format_context(self, retrieved_docs: List[Dict[str, Any]]) -> str:
        """
        Formats the retrieved documents into a numbered list with metadata
        for the LLM to read and cite.
        """
        context_str = ""
        for i, doc in enumerate(retrieved_docs):
            source_file = os.path.basename(doc['metadata'].get('source', 'unknown'))
            page = doc['metadata'].get('page', 'N/A')
            
            # This creates the citation tag [Source X: file=..., page=...]
            citation_tag = f"[Source {i+1}: file={source_file}, page={page}]"
            
            context_str += f"{citation_tag}\n"
            context_str += f"Text: \"{doc['text']}\"\n\n"
            
        return context_str.strip()

    def run(self, query: str, retrieved_docs: List[Dict[str, Any]]) -> str:
        """
        Generates a structured summary with citations based on the query
        and retrieved documents.
        """
        print(f"Summarizing context for query: '{query}'")
        
        # 1. Format the context for the prompt
        formatted_context = self._format_context(retrieved_docs)
        
        # 2. Create the prompt
        prompt = f"""
        [INST]
        You are a professional policy analyst. Your task is to write a structured
        summary that answers the user's query.
        
        Follow these instructions:
        1. Base your answer *only* on the provided "Sources" context.
        2. Do not use any prior knowledge.
        3. For every claim or piece of information you write, you *must* cite the
           source using the `[Source X: file=..., page=...]` tag.
        4. If the context does not contain the answer, state that.
        5. Structure your answer logically (e.g., use bullet points).
        
        ---
        QUERY:
        "{query}"
        ---
        SOURCES:
        {formatted_context}
        ---
        
        STRUCTURED SUMMARY:
        [/INST]
        """
        
        try:
            print("Calling Hugging Face API for summarization...")
            
            response = self.client.chat_completion(
                messages=[{"role": "user", "content": prompt}],
                model=self.MODEL_NAME,
                max_tokens=500, # Give it more room to write a summary
            )
            
            summary = response.choices[0].message.content
            print("✅ Summary generated successfully.")
            return summary
            
        except Exception as e:
            print(f"❌ Error during LLM summarization: {e}")
            return "Error: Could not generate summary."

def save_summary(summary: str, output_file: str):
    """Saves the generated summary to the specified text file."""
    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(summary)


if __name__ == "__main__":
    
    PROJECT_ROOT = Path(__file__).parent.parent.parent
    
    # This is a test file. The final summary will be part of the
    # 'final_policy_brief.txt' generated by the DebateAgents.
    OUTPUT_FILE = PROJECT_ROOT / "results" / "summarizer_test.txt"
    
    print("--- Starting Summarizer Agent (Test Mode) ---")
    
    try:
        agent = SummarizerAgent()
        
        # --- This is a test ---
        # We are simulating the output from the RetrieverAgent
        test_query = "What are the main policies regarding climate change?"
        
        test_docs = [
            {
                "id": "chunk_90",
                "score": 0.5496,
                "text": "CHAPTER 1 gLObaL PROSPECTS aND POLICIES... emissions reduction targets, countries need a holistic set of mitigation instruments, ideally including carbon pricing, public infrastructure investment in clean en...",
                "metadata": {
                    "source": "/home/lenovo/Desktop/Examination_Copy/Data/ch1.pdf",
                    "page": 22
                }
            },
            {
                "id": "chunk_1234",
                "score": 0.5210,
                "text": "The European Union has committed to its 'Green Deal', aiming for carbon neutrality by 2050. This involves significant investment in renewable energy and a circular economy.",
                "metadata": {
                    "source": "/home/lenovo/Desktop/Examination_Copy/Data/eu_policy.pdf",
                    "page": 5
                }
            }
        ]
        
        # Run the agent
        generated_summary = agent.run(test_query, test_docs)
        
        if "Error:" not in generated_summary:
            save_summary(generated_summary, str(OUTPUT_FILE))
            print(f"\n✅ Successfully generated test summary.")
            print(f"Saved summary to {OUTPUT_FILE}")
            print("\nGenerated Summary:")
            print(generated_summary)
        else:
            print("\nFailed to generate a valid summary.")
            
    except Exception as e:
        print(f"\n--- Summarizer Agent Failed ---")
        print(f"Error: {e}")
        
    print("--- Summarizer Agent Finished ---")